return {
  require 'plugins.treesitter',
  require 'plugins.cmp',
  require 'plugins.ts_ls',
  require 'plugins.lsp',
  require 'plugins.snacks',

  require 'plugins.guess_indent',

  require 'plugins.theme',
  require 'plugins.indent_blankline',
  require 'plugins.copilot',
  require 'plugins.database',
  require 'plugins.comment',
  require 'plugins.conform',
  require 'plugins.git',
  require 'plugins.autopairs',
  require 'plugins.trouble',
  require 'plugins.lualine',
  require 'plugins.mini',
  require 'plugins.debug',
  require 'plugins.tests',
  require 'plugins.lint',

  require 'plugins.spoo',
  require 'plugins.claude',
  require 'plugins.devdocs',
  require 'plugins.markdown',
  require 'plugins.vinote',
}
