return {
  require 'plugins.treesitter',
  require 'plugins.cmp',
  require 'plugins.ts_ls',
  require 'plugins.lsp',
  require 'plugins.others',

  require 'plugins.theme',
  require 'plugins.indent_blankline',
  require 'plugins.harpoon',
  require 'plugins.copilot',
  require 'plugins.database',
  require 'plugins.comment',
  require 'plugins.conform',
  require 'plugins.gitsigns',
  require 'plugins.autopairs',
  require 'plugins.trouble',
  require 'plugins.todo',
  require 'plugins.lualine',
  require 'plugins.mini',
  require 'plugins.debug',
  require 'plugins.tests',
  require 'plugins.lint',

  require 'plugins.snacks',
  require 'plugins.spoo',
  require 'plugins.claude',
}
